name: shirne_dialog
description: A flutter package to use alert, toast, popup, snack, imagePreview, loading etc. with customizable style in anywhere.
version: 4.9.0
homepage: https://shirne.github.io/dialog/
repository: https://github.com/shirne/shirne_dialog
screenshots:
  - description: "list of features with some toasts"
    path: screenshots/preview.jpg
topics:
  - dialog
  - toast
  - prompt
  - snack
  - dropdown

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  combined_animation: ">=0.3.1 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  fonts:
    - family: shirne_dialog_icons
      fonts:
        - asset: assets/fonts/icons.ttf
